### ISSUE TITLE
Plus Theme is Missing

### ISSUE THREAD

**Issue by Hyperspeed1313** [LinxGem33/OSX-Arc-Darker#5]
I really don't understand the logic behind removing the plus theme. Bring it back please. I use it.

**Comment by LinxGem33** [comment]
@Hyperspeed1313 

appreciate your feed back, regarding the plus theme it was removed due to Theme parsing errors and other bugs please see [#5](https://github.com/LinxGem33/OSX-Arc-Plus/issues/5) also just to make you aware i have stopped development of OSX Arc theme collection till further notice as i have time constraints which at the moment stops me from offering full support, OSX Arc Plus is still available to manually install from its repository and your more than welcome to work on it.
